GET http://localhost/api/sample

###

POST http://localhost/api/sample
Content-Type: application/json

{
    "hoge": "Hoge",
    "fuga": "Fuga",
    "piyo": "Piyo"
}

###

GET http://localhost/api/sample/1

###

PUT http://localhost/api/sample/1
Content-Type: application/json

{
    "hoge": "Hoge_",
    "fuga": "Fuga",
    "piyo": "Piyo_"
}

###

DELETE http://localhost/api/sample/1
